In [28]:
head(mtcars)

                  mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

In [29]:
#1.1
mtcars[,c(4:8)]

                    hp  drat wt    qsec  vs
Mazda RX4           110 3.90 2.620 16.46 0
Mazda RX4 Wag       110 3.90 2.875 17.02 0
Datsun 710           93 3.85 2.320 18.61 1
Hornet 4 Drive      110 3.08 3.215 19.44 1
Hornet Sportabout   175 3.15 3.440 17.02 0
Valiant             105 2.76 3.460 20.22 1
Duster 360          245 3.21 3.570 15.84 0
Merc 240D            62 3.69 3.190 20.00 1
Merc 230             95 3.92 3.150 22.90 1
Merc 280            123 3.92 3.440 18.30 1
Merc 280C           123 3.92 3.440 18.90 1
Merc 450SE          180 3.07 4.070 17.40 0
Merc 450SL          180 3.07 3.730 17.60 0
Merc 450SLC         180 3.07 3.780 18.00 0
Cadillac Fleetwood  205 2.93 5.250 17.98 0
Lincoln Continental 215 3.00 5.424 17.82 0
Chrysler Imperial   230 3.23 5.345 17.42 0
Fiat 128             66 4.08 2.200 19.47 1
Honda Civic          52 4.93 1.615 18.52 1
Toyota Corolla       65 4.22 1.835 19.90 1
Toyota Corona        97 3.70 2.465 20.01 1
Dodge Challenger    150 2.76 3.520 16.87 0
AMC Javelin         150 3.15 3.435 17.30 0
Camaro Z28          245 3.73 3.840 15.41 0
Pontiac Firebird    175 3.08 3.845 17.05 0
Fiat X1-9            66 4.08 1.935 18.90 1
Porsche 914-2        91 4.43 2.140 16.70 0
Lotus Europa        113 3.77 1.513 16.90 1
Ford Pantera L      264 4.22 3.170 14.50 0
Ferrari Dino        175 3.62 2.770 15.50 0
Maserati Bora       335 3.54 3.570 14.60 0
Volvo 142E          109 4.11 2.780 18.60 1

In [30]:
#1.2
high_hp = mtcars$hp > 100
mtcars[high_hp,]

                    mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [33]:
#1.3
mtcars[order(mtcars$mpg),]

                    mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1

In [35]:
#1.4
mtcars <-transform(mtcars,wt1000=wt*1000)
mtcars

                    mpg  cyl disp  hp  drat wt    qsec  vs am gear carb wt1000
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4    2620
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4    2875
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1    2320
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1    3215
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2    3440
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1    3460
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4    3570
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2    3190
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2    3150
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4    3440
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4    3440
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3    4070
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3    3730
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3    3780
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4    5250
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4    5424
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4    5345
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1    2200
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2    1615
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1    1835
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1    2465
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2    3520
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2    3435
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4    3840
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2    3845
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1    1935
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2    2140
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2    1513
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4    3170
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6    2770
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8    3570
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2    2780

In [7]:
mylist=list(sex = c(1,1,1,1,2,2,2,2,2,2), smoking = c(1,0,1,0,1,0,0,0,1,1), age=c(21:30))

In [8]:
#2.1
lapply(mylist, function(kk){ kk*2 })

$sex
 [1] 2 2 2 2 4 4 4 4 4 4

$smoking
 [1] 2 0 2 0 2 0 0 0 2 2

$age
 [1] 42 44 46 48 50 52 54 56 58 60

In [9]:
#2.2
sapply(mylist, min)

    sex smoking     age
      1       0      21

In [ ]:
#2.3
#yes, there is difference between lapply and sapply. lapply give the entire set for the output by looping over 
#all elements.  sapply is does the same thing as lapply but simplifies the output to the required condition

In [20]:
#5.1,5.2
var = read.delim("test.txt")
var
class(var)

  Index symbol color
1 1     A      red
2 2     B      red
3 3     C      red
4 4     D      red
5 5     E      red
6 6     F      red

[1] "data.frame"

In [22]:
#6
zz=matrix(c(c(1,2,NA), c(3,4,5), 6:9), nrow = 2, ncol = 5, byrow = TRUE)
zz

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    2    NA   3    4
[2,] 5    6     7   8    9

In [23]:
#6
apply(zz,1,sum)

[1] NA 35

In [26]:
#6
apply(zz,2,mean)

[1] 3.0 4.0  NA 5.5 6.5

In [36]:
#7 1,2,3
alphabet<-data.frame(index=1:26,color=c(rep('red',10),rep('green',6),rep('blue',10)))
#For a rows of alphabet whose index>10 and index<20
subset(alphabet,index>10 & index <20)
#For a rows of alphabet whose color=='red' or index <10
subset(alphabet,color=='red' | index<10)

   index color
11 11    green
12 12    green
13 13    green
14 14    green
15 15    green
16 16    green
17 17    blue
18 18    blue
19 19    blue

   index color
1   1    red
2   2    red
3   3    red
4   4    red
5   5    red
6   6    red
7   7    red
8   8    red
9   9    red
10 10    red