In [3]:
# Question
# ### Homework Assignment 2. 
# ### Find the two most correlated stocks.

# #### The sample correlation coefficient formula is

# <img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/332ae9dcde34d03f30ed6e1880af8b43327dd49c">

# #### where ${\overline {x}}$ and ${\overline {y}}$ are the sample means of $[x1, x2, ..., xn]$ and $[y1, y2, ..., yn]$

# ### Data Preparation

# Download the historial daily data of the entire 2018 for the 6 stocks 

# ```python
# tks = ['IBM', 'MSFT', 'GOOG', 'AAPL', 'AMZN', 'FB']
# ```

# For example, to download IBM data, use the following link to go to yahoo finance page. Find the "Download Data" link to download the csv file to you local disk.
# https://finance.yahoo.com/quote/IBM/history?period1=1514782800&period2=1546232400&interval=1d&filter=history&frequency=1d

# Replace "IBM" with other stock symbol in the above URL, you will be able to download data for other 5 stocks.

# You should have 6 csv files on your disk now. IBM.csv, MSFT.csv, etc. Each of the csv file should look like,

# ![image.png](attachment:image.png)

# ### Retrieve the "Adj Close" column values as the daily prices of each stock

# Load the data into data frame and retrieve the "Adj Close" column values


# ### Compute the correlation between any two stocks' "Adj Close" prices. 

# You should use the above formula to implement the correlation algorithm. Do not use any type of looping.

# ### Conclusion

# Use apply functions here. Print all stock pairs and their correlations from max to min. The format should look like below. The numbers here are dummy numbers.

# ```python
# IBM:MSFT = 0.763
# IBM:GOOG = 0.627
# ...
# AMZN:FB = 0.234
# ```
# #### Tips: By definition, the correlation is symmetrical, i.e., r_xy = r_yx, so when you have IBM:MSFT, you can skip MSFT:IBM.

# ### Please submit your jupyter notebook to canvas.

In [18]:
#Load the data into dataframe and retrieve the "Adj Close" column values
df.ibm = data.frame(read.csv("IBM.csv"))[,6]
df.aapl = data.frame(read.csv("AAPL.csv"))[,6]
df.amzn = data.frame(read.csv("AMZN.csv"))[,6]
df.fb = data.frame(read.csv("FB.csv"))[,6]
df.goog = data.frame(read.csv("GOOG.csv"))[,6]
df.msft = data.frame(read.csv("MSFT.csv"))[,6]

In [19]:
#user built correlation function using given formula
corfun = function(x,y){
    n = sum((x - mean(x)) * (y - mean(y)))
    d = sqrt(sum((x - mean(x)) ** 2) * sum((y - mean(y)) ** 2))
    r = n / d
    print(r)
}

In [20]:
all=list(df.ibm,df.msft,df.aapl,df.amzn,df.fb,df.goog) #creating a list of all companies
cor.ibm = rbind(sapply(all,corfun,all[[1]]))
cor.msft = rbind(sapply(all,corfun,all[[2]]))
cor.aapl = rbind(sapply(all,corfun,all[[3]]))
cor.amzn = rbind(sapply(all,corfun,all[[4]]))
cor.fb = rbind(sapply(all,corfun,all[[5]]))
cor.goog = rbind(sapply(all,corfun,all[[6]]))
cor.all = rbind(cor.ibm,cor.msft,cor.aapl,cor.amzn,cor.fb,cor.goog)
names = c('IBM', 'MSFT', 'AAPL', 'AMZN', 'FB', 'GOOG')
rownames(cor.all) = names
colnames(cor.all) = names
cor.all #matrix of all corellations between 2 companies

[1] 1
[1] -0.4212552
[1] -0.02471866
[1] -0.1017012
[1] 0.6235316
[1] 0.4224399
[1] -0.4212552
[1] 1
[1] 0.7910725
[1] 0.8741709
[1] -0.2952496
[1] 0.4633164
[1] -0.02471866
[1] 0.7910725
[1] 1
[1] 0.8405048
[1] -0.03871685
[1] 0.5831373
[1] -0.1017012
[1] 0.8741709
[1] 0.8405048
[1] 1
[1] 0.04804593
[1] 0.6593919
[1] 0.6235316
[1] -0.2952496
[1] -0.03871685
[1] 0.04804593
[1] 1
[1] 0.5255643
[1] 0.4224399
[1] 0.4633164
[1] 0.5831373
[1] 0.6593919
[1] 0.5255643
[1] 1

     IBM         MSFT       AAPL        AMZN        FB          GOOG
IBM   1.00000000 -0.4212552 -0.02471866 -0.10170124  0.62353159 0.4224399
MSFT -0.42125516  1.0000000  0.79107247  0.87417092 -0.29524956 0.4633164
AAPL -0.02471866  0.7910725  1.00000000  0.84050480 -0.03871685 0.5831373
AMZN -0.10170124  0.8741709  0.84050480  1.00000000  0.04804593 0.6593919
FB    0.62353159 -0.2952496 -0.03871685  0.04804593  1.00000000 0.5255643
GOOG  0.42243985  0.4633164  0.58313735  0.65939187  0.52556430 1.0000000

In [31]:
count = 1
result = matrix(nrow = 15, ncol = 2)
for(i in 2:6){
    for(j in 1:(i-1)){
        result[count,1] = paste(names[j] ,':', names[i],'=')
        result[count,2] = round(cor.all[i,j],3)
        count = count + 1
    }
}

In [32]:
result[order(result[,2],decreasing=TRUE),]

      [,1]          [,2]
 [1,] MSFT : AMZN = 0.874
 [2,] AAPL : AMZN = 0.841
 [3,] MSFT : AAPL = 0.791
 [4,] AMZN : GOOG = 0.659
 [5,] IBM : FB =    0.624
 [6,] AAPL : GOOG = 0.583
 [7,] FB : GOOG =   0.526
 [8,] MSFT : GOOG = 0.463
 [9,] IBM : GOOG =  0.422
[10,] AMZN : FB =   0.048
[11,] IBM : MSFT =  -0.421
[12,] MSFT : FB =   -0.295
[13,] IBM : AMZN =  -0.102
[14,] AAPL : FB =   -0.039
[15,] IBM : AAPL =  -0.025